Digital_Grid-Django/calculator/urls.py
from django.urls import path
from calculator import views



urlpatterns = [

    path("", views.view1, name="calculator"),
    #path("/", views.view2, name=""),

]

Digital_Grid-Django/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("calculator.urls")),
]

Digital_Grid-Django/calculator/models.py
from django.db import models



class DiscountRules(models.Model):


    TYPE_CHOICES = (
        ("R","Residencial"),
        ("C","Comercial"),
        ("I","Industrial"),
    )

    RANGE_CHOICES = (
        ("B","< 10.000 kWh"),
        ("M",">= 10.000 kWh e <= 20.000 kWh"),
        ("A","> 20.000 kWh"),
    )

    COVER_CHOICES = (
        ("B","< 10.000 kWh"),
        ("M",">= 10.000 kWh e <= 20.000 kWh"),
        ("A","> 20.000 kWh"),
    )

    consumer_type = models.CharField("Tipo do Consumidor", max_length=1, choices=TYPE_CHOICES)
    consumption_range = models.CharField("Faixa de Consumo", max_length=1, choices=RANGE_CHOICES)
    cover_value = models.CharField("Valor de Cobertura", max_length=1, choices=COVER_CHOICES)
    discount_value = models.DecimalField("Valor de Desconto", decimal_places=2, max_digits=10)



class Consumer(models.Model):


    name = models.CharField("Nome do Consumidor", max_length=128)
    document = models.CharField("Documento(CPF/CNPJ)", max_length=14, unique=True)
    zip_code = models.CharField("CEP", max_length=8, null=True, blank=True)
    city = models.CharField("Cidade", max_length=128)
    state = models.CharField("Estado", max_length=128)
    consumption = models.IntegerField("Consumo(kWh)", blank=True, null=True)
    distributor_tax = models.FloatField("Tarifa da Distribuidora", blank=True, null=True)
    discount_rule = models.ForeignKey(DiscountRules, on_delete=models.CASCADE)
    # create the foreign key for discount rule model here

    def __str__(self):
            return str(self.name)


# TODO: Create the model DiscountRules below
"""Fields:
-> Consumer type  
-> Consumption range
-> Cover value
-> Discount value
The first three fields should be a select with the values provided in the table
defined in the readme of the repository. Discount should be numerical
"""

# TODO: You must populate the consumer table with the data provided in the file consumers.xlsx
#  and associate each one with the correct discount rule

Digital_Grid-Django/calculator/views.py
from django.shortcuts import render
from calculator.models import Consumer

# TODO: Your list view should do the following tasks
"""
-> Recover all consumers from the database
-> Get the discount value for each consumer
-> Calculate the economy
-> Send the data to the template that will be rendered
"""



def view1(request):
    
    consumers = Consumer.objects.all()

    context = {
        'consumers': consumers,
    }
    return render(request, 'calculator/list.html', context)


# TODO: Your create view should do the following tasks
"""Create a view to perform inclusion of consumers. The view should do:
-> Receive a POST request with the data to register
-> If the data is valid (validate document), create and save a new Consumer object associated with the right discount rule object
-> Redirect to the template that list all consumers

Your view must be associated with an url and a template different from the first one. A link to
this page must be provided in the main page.
"""


def view2():
    # Create the second view here.
    pass

Digital_Grid-Django/calculator/templates/calculator/_base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container-fluid">
        <div class="row">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

Digital_Grid-Django/calculator/templates/calculator/list.html
{% extends 'calculator/_base.html' %}
<!--
TODO: You must display the consumer sent to the template in a table with the follow headers
 - Nome, Documento, Consumo, Tipo, Cobertura, Desconto, Economia

TODO: You must provide 2 selects to filter the rows based in:
 1) consumer type
 2) consumption range
 - You must create the filter functionality in the front-end using JS
-->

{% block title %}Calculadora{% endblock %}

{% block content %}

    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Documento</th>
            <th scope="col">Consumo</th>
            <th scope="col">Tipo</th>
            <th scope="col">Cobertura</th>
            <th scope="col">Desconto</th>
            <th scope="col">Economia</th>
          </tr>
        </thead>
        <tbody>
        {% if consumers %}
          {% for consumer in consumers %}
          <tr>
            <th scope="row">{{ consumer.id }}</th>
            <td>{{ consumer.name }}</td>
            <td>{{ consumer.document }}</td>
            <td>{{ consumer.consumption }} kWh</td>
            <td>{{ consumer.discount_rule.get_consumer_type_display }}</td>
            <td>{{ consumer.discount_rule.get_cover_value_display }}</td>
            <td>{{ consumer.discount_rule.discount_value }}</td>
            <td>{{ consumer.discount_rule.discount_value }}</td>
          </tr>
          {% endfor %}
        {% else %}
          <tr>
            <th scope="row" colspan="9">Nenhum consumidor encontrado.</th>
          </tr>
        {% endif %}
        </tbody>
      </table>

{% endblock %}